url: https://swift.swiftgg.team
title: SwiftGG
description: "Swift 是一种通用编程语言，它采用现代方法处理安全性、性能和软件设计模式。"
timezone: America/Lower_Princes
exclude: ["README.md", "config.ru", "Gemfile", "Gemfile.lock", "Procfile", "vendor"]
safe: false
future: true

kramdown:
    syntax_highlighter: rouge

sass:
    style: compressed
    sass_dir: "assets/stylesheets"

defaults:
    -
        scope:
            type: "posts"
        values:
            permalink: /blog/:title/
            layout: "post"

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
